name: CI CD Application Deployment

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Cloning Repository
        uses: actions/checkout@v3

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Check Node Version
        run: node --version

      - name: Install Dependencies
        run: npm install

      - name: Print Test Report
        run: npm run check
        
      - name: Send WhatsApp Message
        run: |
          curl -X POST https://api.twilio.com/2010-04-01/Accounts/${{ secrets.TWILIO_ACCOUNT_SID }}/Messages.json \
          --data-urlencode "From=${{ secrets.TWILIO_FROM_NUMBER }}" \
          --data-urlencode "To=${{ secrets.TWILIO_TO_NUMBER }}" \
          --data-urlencode "Body=✅ Test Completed. Check Results: <insert URL or summary>" \
          -u ${{ secrets.TWILIO_ACCOUNT_SID }}:${{ secrets.TWILIO_AUTH_TOKEN }}

  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: print Hello World
        run: echo "Hello World"