name: CI CD Application Deployment

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Cloning Repository
        uses: actions/checkout@v3

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Check Node Version
        run: node --version

      - name: Install Dependencies
        run: npm install
      - name: Print Repository
        run: npm run check

  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: print Hello World
        run: echo "Hello World"